# Generated by Django 5.2.1 on 2025-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_consignee_customer_shipper_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Carrier Name')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': '4. Carriers',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Operator Name')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': '5. Operators',
            },
        ),
        migrations.AddField(
            model_name='consignee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID'),
        ),
    ]
