# Generated by Django 5.2.1 on 2025-10-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_carrier_operator_consignee_national_id'),
        ('shipment_module', '0011_alter_shipment_operators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
