# Generated by Django 5.2.1 on 2025-10-25 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pod')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name')),
                ('country_abbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Abbr')),
                ('airport_abbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='Airport Abbr')),
            ],
            options={
                'verbose_name': 'Pod',
                'verbose_name_plural': '3. Pods',
            },
        ),
        migrations.CreateModel(
            name='PolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pol')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name')),
                ('country_abbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Abbr')),
                ('airport_abbr', models.CharField(blank=True, max_length=5, null=True, verbose_name='Airport Abbr')),
            ],
            options={
                'verbose_name': 'Pol',
                'verbose_name_plural': '2. Pols',
            },
        ),
        migrations.CreateModel(
            name='TermList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': '4. Terms',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref.No.')),
                ('marketing_channel', models.CharField(max_length=100, verbose_name='Marketing Channel')),
                ('inq_sent', models.BooleanField(default=False, verbose_name='INQ SENT')),
                ('inq_replied', models.BooleanField(default=False, verbose_name='INQ REPLIED')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('via', models.CharField(blank=True, max_length=255, null=True, verbose_name='VIA')),
                ('console', models.BooleanField(default=False, verbose_name='Console')),
                ('console_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Console No')),
                ('mawb', models.CharField(blank=True, max_length=255, null=True, verbose_name='MAWB')),
                ('hawb', models.CharField(blank=True, max_length=255, null=True, verbose_name='HAWB')),
                ('etdw', models.DateField(blank=True, null=True, verbose_name='ETD W')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('pcs', models.CharField(blank=True, max_length=255, null=True, verbose_name='PCS')),
                ('gw', models.CharField(blank=True, max_length=255, null=True, verbose_name='G.W')),
                ('vol', models.CharField(blank=True, max_length=255, null=True, verbose_name='VOL')),
                ('cw', models.CharField(blank=True, max_length=255, null=True, verbose_name='C.W')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('commodity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commodity')),
                ('manifest_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manifest No')),
                ('hscode', models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Code')),
                ('extra_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extra Charges')),
                ('transit_time', models.IntegerField(blank=True, null=True, verbose_name='Transit Time (days)')),
                ('airfreight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pickup', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custom_clearance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('do_clearance_ika', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='D/O + Clearance IKA (IRR)')),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Transfer Fee (2%)')),
                ('other_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Other Charges (S/AWB, AAI, AMS, AWB/PCA)')),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (USD)')),
                ('grand_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Grand Total (USD)')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.carrier', verbose_name='Carrier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_client', to='account.customer', verbose_name='Client')),
                ('cnee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_cnee', to='account.consignee', verbose_name='MAWB Cnee')),
                ('hawb_cnee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawb_cnee_shipments', to='account.consignee', verbose_name='HAWB Cnee')),
                ('hawb_shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawb_shipments', to='account.shipper', verbose_name='HAWB Shipper')),
                ('operators', models.ManyToManyField(blank=True, related_name='operator_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Operators')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_module.podlist', verbose_name='Pod')),
                ('pol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_module.pollist', verbose_name='Pol')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_shipper', to='account.shipper', verbose_name='MAWB Shipper')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_sp', to=settings.AUTH_USER_MODEL, verbose_name='S/P')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment_module.termlist', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': '1. Shipments',
            },
        ),
    ]
