# Generated by Django 5.2.1 on 2025-06-01 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(max_length=255, verbose_name="Ref.No.")),
                (
                    "inq_sent",
                    models.BooleanField(default=False, verbose_name="INQ SENT"),
                ),
                (
                    "inq_replied",
                    models.BooleanField(default=False, verbose_name="INQ REPLIED"),
                ),
                (
                    "confirm_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmation Date"
                    ),
                ),
                ("via", models.CharField(max_length=255, verbose_name="VIA")),
                ("carrier", models.CharField(max_length=255, verbose_name="Carrier")),
                ("console", models.BooleanField(default=False, verbose_name="Console")),
                (
                    "console_no",
                    models.BooleanField(default=False, verbose_name="Console No"),
                ),
                ("mawb", models.CharField(max_length=255, verbose_name="MAWB")),
                ("hawb", models.CharField(max_length=255, verbose_name="HAWB")),
                (
                    "etdw",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETD W"),
                ),
                (
                    "etd",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETD"),
                ),
                (
                    "eta",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETA"),
                ),
                (
                    "transfer_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Transfer Time"
                    ),
                ),
                ("pol", models.CharField(max_length=255, verbose_name="Pol")),
                ("pod", models.CharField(max_length=255, verbose_name="Pod")),
                ("term", models.CharField(max_length=255, verbose_name="Term")),
                ("pcs", models.CharField(max_length=255, verbose_name="PCS")),
                ("gw", models.CharField(max_length=255, verbose_name="G.W")),
                ("vol", models.CharField(max_length=255, verbose_name="VOL")),
                ("cw", models.CharField(max_length=255, verbose_name="C.W")),
                ("currency", models.CharField(max_length=255, verbose_name="Currency")),
                (
                    "commodity",
                    models.CharField(max_length=255, verbose_name="Currency"),
                ),
                ("hshipper", models.CharField(max_length=255, verbose_name="HShipper")),
                ("hcnee", models.CharField(max_length=255, verbose_name="HCnee")),
                ("shipper", models.CharField(max_length=255, verbose_name="Shipper")),
                ("Cnee", models.CharField(max_length=255, verbose_name="Cnee")),
                (
                    "manifest_no",
                    models.CharField(max_length=255, verbose_name="Manifest No"),
                ),
                (
                    "epl_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETD"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "sp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_sp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="S/P",
                    ),
                ),
            ],
        ),
    ]
