# Generated by Django 5.2.1 on 2025-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref.No.'),
        ),
    ]
