# Generated by Django 5.2.1 on 2026-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="flight_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Flight Number"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="invoice_issued",
            field=models.BooleanField(default=False, verbose_name="Invoice Issued"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Done"),
        ),
    ]
