# Generated by Django 5.2.1 on 2025-06-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="console_no",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Console No"
            ),
        ),
    ]
