# Generated by Django 5.2.1 on 2026-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="flight_number",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Flight Number"
            ),
        ),
    ]
