# Generated by Django 5.2.1 on 2026-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="extra_charges",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=50,
                null=True,
                verbose_name="Extra Charges",
            ),
        ),
    ]
