# Generated by Django 5.2.1 on 2026-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0002_alter_shipment_extra_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='extra_charges',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Extra Charges'),
        ),
    ]
