# Generated by Django 5.2.1 on 2026-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0002_alter_charge_amount_alter_shipment_extra_charges"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charge",
            options={"verbose_name": "Charge", "verbose_name_plural": "10. Charges"},
        ),
        migrations.AlterModelOptions(
            name="console",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Console",
                "verbose_name_plural": "9. Consoles",
            },
        ),
        migrations.AlterModelOptions(
            name="podlist",
            options={"verbose_name": "Pod", "verbose_name_plural": "8. Pods"},
        ),
        migrations.AlterModelOptions(
            name="pollist",
            options={"verbose_name": "Pol", "verbose_name_plural": "7. Pols"},
        ),
    ]
