# Generated by Django 5.2.1 on 2026-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment_module",
            "0002_shipment_flight_number_shipment_invoice_issued_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="confirm_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Confirmation Date"
            ),
        ),
    ]
