# Generated by Django 5.2.1 on 2025-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0002_alter_shipment_console_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Carrier"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="via",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="VIA"
            ),
        ),
    ]
