# Generated by Django 5.2.1 on 2026-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0002_alter_shipment_flight_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="invoice_issued",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Invoice Issued"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="payment_done",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Payment Done"
            ),
        ),
    ]
