# Generated by Django 5.2.1 on 2025-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0003_alter_shipment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Ref.No.'),
        ),
    ]
