# Generated by Django 5.2.1 on 2025-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0003_alter_shipment_carrier_alter_shipment_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="confirm_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Confirmation Date"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="epl_date",
            field=models.DateField(blank=True, null=True, verbose_name="ETD"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="eta",
            field=models.DateField(blank=True, null=True, verbose_name="ETA"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="etd",
            field=models.DateField(blank=True, null=True, verbose_name="ETD"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="etdw",
            field=models.DateField(blank=True, null=True, verbose_name="ETD W"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="transfer_time",
            field=models.DateField(blank=True, null=True, verbose_name="Transfer Time"),
        ),
    ]
