# Generated by Django 5.2.1 on 2025-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0004_alter_shipment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice_deadline',
            field=models.BooleanField(default=False, verbose_name='Invoice Deadline'),
        ),
    ]
