# Generated by Django 5.2.1 on 2025-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment_module",
            "0004_alter_shipment_confirm_date_alter_shipment_epl_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Shipment", "verbose_name_plural": "Shipments"},
        ),
        migrations.AlterField(
            model_name="shipment",
            name="commodity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="currency",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="hcnee",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="HCnee"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="hshipper",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="HShipper"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="manifest_no",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Manifest No"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipper",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Shipper"
            ),
        ),
    ]
