# Generated by Django 5.2.1 on 2026-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0005_shipment_invoice_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="flight_number",
            field=models.CharField(blank=True, null=True, verbose_name="Flight Number"),
        ),
    ]
