# Generated by Django 5.2.1 on 2026-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0005_alter_shipment_extra_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='extra_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Extra Charges'),
        ),
    ]
