# Generated by Django 5.2.1 on 2025-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipment_module",
            "0005_alter_shipment_options_alter_shipment_commodity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="Cnee",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cnee"
            ),
        ),
    ]
