# Generated by Django 5.2.1 on 2025-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0006_alter_shipment_cnee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="cw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="C.W"
            ),
        ),
    ]
