# Generated by Django 5.2.1 on 2026-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0006_shipment_flight_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="invoice_issued",
            field=models.BooleanField(default=False, verbose_name="Invoice Issued"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="payment_done",
            field=models.BooleanField(default=False, verbose_name="Payment Done"),
        ),
    ]
