# Generated by Django 5.2.1 on 2026-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0007_shipment_invoice_issued_shipment_payment_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="flight_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Flight Number"
            ),
        ),
    ]
