# Generated by Django 5.2.1 on 2025-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment_module", "0007_alter_shipment_cw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="epl_date",
            field=models.DateField(blank=True, null=True, verbose_name="EPL Date"),
        ),
    ]
