# Generated by Django 5.2.1 on 2025-10-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_consignee_customer_shipper_alter_user_options"),
        ("shipment_module", "0008_alter_shipment_epl_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pod"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pod",
                "verbose_name_plural": "3. Pods",
            },
        ),
        migrations.CreateModel(
            name="PolList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pol"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pol",
                "verbose_name_plural": "2. Pols",
            },
        ),
        migrations.CreateModel(
            name="TermList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Term"
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "4. Terms",
            },
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Shipment", "verbose_name_plural": "1. Shipments"},
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="Cnee",
        ),
        migrations.AlterField(
            model_name="shipment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_client",
                to="account.customer",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="commodity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Commodity"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="gw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="G.W"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="hawb",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="HAWB"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="mawb",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="MAWB"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="pcs",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PCS"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_shipper",
                to="account.shipper",
                verbose_name="Shipper",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="vol",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="VOL"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="pod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment_module.podlist",
                verbose_name="Pod",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="pol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment_module.pollist",
                verbose_name="Pol",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipment_module.termlist",
                verbose_name="Term",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cnee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_cnee",
                to="account.consignee",
                verbose_name="Cnee",
            ),
        ),
    ]
