# Generated by Django 5.2.1 on 2025-10-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_carrier_operator_consignee_national_id'),
        ('shipment_module', '0009_podlist_pollist_termlist_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='epl_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='hcnee',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='hshipper',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='transfer_time',
        ),
        migrations.AddField(
            model_name='podlist',
            name='airport_abbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Airport Abbr'),
        ),
        migrations.AddField(
            model_name='podlist',
            name='country_abbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Abbr'),
        ),
        migrations.AddField(
            model_name='podlist',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='pollist',
            name='airport_abbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Airport Abbr'),
        ),
        migrations.AddField(
            model_name='pollist',
            name='country_abbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Abbr'),
        ),
        migrations.AddField(
            model_name='pollist',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='extra_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extra Charges'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hawb_cnee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawb_cnee_shipments', to='account.consignee', verbose_name='HAWB Cnee'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hawb_shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hawb_shipments', to='account.shipper', verbose_name='HAWB Shipper'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='hscode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='marketing_channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marketing Channel'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='account.operator', verbose_name='Operators'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transit_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Transit Time (days)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.carrier', verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cnee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_cnee', to='account.consignee', verbose_name='MAWB Cnee'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref.No.'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_shipper', to='account.shipper', verbose_name='MAWB Shipper'),
        ),
    ]
