# Generated by Django 5.2.1 on 2025-10-15 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0010_remove_shipment_epl_date_remove_shipment_hcnee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operator_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Operators'),
        ),
    ]
