# Generated by Django 5.2.1 on 2025-10-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_module', '0011_alter_shipment_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='airfreight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='custom_clearance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='do_clearance_ika',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='D/O + Clearance IKA (IRR)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='grand_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Grand Total (USD)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='other_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Other Charges (S/AWB, AAI, AMS, AWB/PCA)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (USD)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transfer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Transfer Fee (2%)'),
        ),
    ]
