# Generated by Django 5.2.1 on 2026-09-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("shipment_module", "0003_alter_charge_options_alter_console_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="شماره رفرانس داخلی پرونده",
                        max_length=20,
                        unique=True,
                        verbose_name="Ref",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("fcl", "FCL"), ("lcl", "LCL"), ("bb", "Break Bulk")],
                        default="fcl",
                        max_length=3,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "movement",
                    models.CharField(
                        choices=[
                            ("cy-cy", "CY / CY"),
                            ("cy-cfs", "CY / CFS"),
                            ("cfs-cy", "CFS / CY"),
                            ("cfs-cfs", "CFS / CFS"),
                            ("dr-cy", "Door / CY"),
                            ("dr-dr", "Door / Door"),
                        ],
                        default="cy-cy",
                        help_text="نوع سرویس حمل",
                        max_length=10,
                        verbose_name="Movement",
                    ),
                ),
                (
                    "place_of_receipt",
                    models.CharField(
                        blank=True,
                        help_text="محل تحویل بار به کشتیرانی",
                        max_length=100,
                        null=True,
                        verbose_name="Place of Receipt",
                    ),
                ),
                (
                    "final_destination",
                    models.CharField(
                        blank=True,
                        help_text="مقصد نهایی (مثل گمرک شهریار)",
                        max_length=100,
                        null=True,
                        verbose_name="Final Destination",
                    ),
                ),
                (
                    "bl_release",
                    models.CharField(
                        choices=[
                            ("original", "Original B/L"),
                            ("telex", "Telex Release / Surrendered"),
                            ("waybill", "Express / Sea Waybill"),
                        ],
                        default="original",
                        help_text="نوع آزادسازی بارنامه",
                        max_length=10,
                        verbose_name="B/L Release",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Priority"
                    ),
                ),
                (
                    "inq_replied",
                    models.BooleanField(
                        default=False, verbose_name="Inquiry Replied (RPL)"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="CFM (Confirmed)"),
                ),
                (
                    "cfm_date",
                    models.DateField(blank=True, null=True, verbose_name="CFM Date"),
                ),
                (
                    "vessel_name",
                    models.CharField(
                        help_text="نام کشتی", max_length=100, verbose_name="Vessel"
                    ),
                ),
                (
                    "voyage_no",
                    models.CharField(
                        help_text="شماره سفر", max_length=30, verbose_name="Voyage No"
                    ),
                ),
                (
                    "mbl_no",
                    models.CharField(
                        blank=True,
                        help_text="Master Bill of Lading",
                        max_length=50,
                        null=True,
                        verbose_name="MBL No",
                    ),
                ),
                (
                    "hbl_no",
                    models.CharField(
                        blank=True,
                        help_text="House Bill of Lading",
                        max_length=50,
                        null=True,
                        verbose_name="HBL No",
                    ),
                ),
                (
                    "booking_no",
                    models.CharField(
                        blank=True,
                        help_text="شماره بوکینگ / S/O",
                        max_length=50,
                        null=True,
                        verbose_name="Booking No",
                    ),
                ),
                (
                    "manifest_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Manifest No"
                    ),
                ),
                (
                    "mbl_shipper",
                    models.TextField(blank=True, null=True, verbose_name="MBL Shipper"),
                ),
                (
                    "mbl_cnee",
                    models.TextField(
                        blank=True, null=True, verbose_name="MBL Consignee"
                    ),
                ),
                (
                    "hbl_shipper",
                    models.TextField(blank=True, null=True, verbose_name="HBL Shipper"),
                ),
                (
                    "hbl_cnee",
                    models.TextField(
                        blank=True, null=True, verbose_name="HBL Consignee"
                    ),
                ),
                (
                    "notify_party",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notify Party"
                    ),
                ),
                (
                    "delivery_agent",
                    models.TextField(
                        blank=True,
                        help_text="نماینده تحویل\u200cدهنده بار در مقصد",
                        null=True,
                        verbose_name="Delivery Agent",
                    ),
                ),
                (
                    "container_no",
                    models.CharField(
                        blank=True,
                        help_text="شماره کانتینر (چندتایی با کاما)",
                        max_length=100,
                        null=True,
                        verbose_name="Container No",
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        blank=True,
                        help_text="مثل 20GP / 40HC / 40NOR",
                        max_length=10,
                        null=True,
                        verbose_name="Container Type",
                    ),
                ),
                (
                    "seal_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Seal No"
                    ),
                ),
                (
                    "pcs",
                    models.CharField(
                        help_text="تعداد و نوع بسته بندی مثل: 2 WOODEN CASES",
                        max_length=50,
                        verbose_name="Packages",
                    ),
                ),
                (
                    "marks",
                    models.CharField(
                        blank=True,
                        help_text="مثل N/M",
                        max_length=100,
                        null=True,
                        verbose_name="Marks & Numbers",
                    ),
                ),
                (
                    "commodity",
                    models.TextField(help_text="شرح کالا", verbose_name="Commodity"),
                ),
                (
                    "hscode",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="HS Code"
                    ),
                ),
                (
                    "gw",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="وزن ناخالص",
                        max_digits=12,
                        verbose_name="G.W (Kg)",
                    ),
                ),
                (
                    "vol",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Volume (CBM)"
                    ),
                ),
                (
                    "cw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="وزن محاسباتی - Revenue Ton (برای LCL)",
                        max_digits=10,
                        null=True,
                        verbose_name="Chargeable W / R.T",
                    ),
                ),
                ("etd", models.DateField(blank=True, null=True, verbose_name="ETD")),
                (
                    "atd",
                    models.DateField(
                        blank=True,
                        help_text="تاریخ واقعی حرکت (Shipped on Board)",
                        null=True,
                        verbose_name="ATD",
                    ),
                ),
                ("eta", models.DateField(blank=True, null=True, verbose_name="ETA")),
                ("ata", models.DateField(blank=True, null=True, verbose_name="ATA")),
                (
                    "freight_term",
                    models.CharField(
                        choices=[("prepaid", "Prepaid"), ("collect", "Collect")],
                        default="prepaid",
                        max_length=10,
                        verbose_name="Freight",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "ocean_freight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Ocean Freight",
                    ),
                ),
                (
                    "thc_pol",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="THC (POL)",
                    ),
                ),
                (
                    "thc_pod",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="THC (POD)",
                    ),
                ),
                (
                    "pickup_inland",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Pickup / Inland",
                    ),
                ),
                (
                    "customs_clearance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Customs Clearance",
                    ),
                ),
                (
                    "do_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="D/O Fee",
                    ),
                ),
                (
                    "transit_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Transit Fee",
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Other Charges",
                    ),
                ),
                (
                    "extra_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Extra Charges",
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="Total (USD)",
                    ),
                ),
                (
                    "grand_total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="Grand Total (USD)",
                    ),
                ),
                (
                    "invoice_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Invoice Deadline"
                    ),
                ),
                (
                    "invoice_issued",
                    models.BooleanField(default=False, verbose_name="Invoice Issued"),
                ),
                (
                    "payment_done",
                    models.BooleanField(default=False, verbose_name="Payment Done"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="account.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="account.customer",
                        verbose_name="Client",
                    ),
                ),
                (
                    "console",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="shipment_module.console",
                        verbose_name="Console",
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Operators",
                    ),
                ),
                (
                    "pod",
                    models.ForeignKey(
                        help_text="Port of Discharge - بندر تخلیه",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments_pod",
                        to="shipment_module.podlist",
                        verbose_name="P.O.D",
                    ),
                ),
                (
                    "pol",
                    models.ForeignKey(
                        help_text="Port of Loading - بندر بارگیری",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments_pol",
                        to="shipment_module.pollist",
                        verbose_name="P.O.L",
                    ),
                ),
                (
                    "sp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="S/P",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Incoterms",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="shipment_module.termlist",
                        verbose_name="Term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sea Shipment",
                "verbose_name_plural": "Sea Shipments",
                "ordering": ["-created_at"],
            },
        ),
    ]
