# Generated by Django 5.2.1 on 2026-09-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_no",
                    models.CharField(max_length=20, verbose_name="Container No"),
                ),
                (
                    "seal_no",
                    models.CharField(blank=True, max_length=30, verbose_name="Seal No"),
                ),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("20GP", "20' General Purpose"),
                            ("40GP", "40' General Purpose"),
                            ("40HQ", "40' High Cube"),
                            ("20RF", "20' Reefer"),
                            ("40RF", "40' Reefer"),
                            ("20OT", "20' Open Top"),
                            ("40OT", "40' Open Top"),
                            ("40FR", "40' Flat Rack"),
                        ],
                        default="40HQ",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "gw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight (KG)",
                    ),
                ),
                (
                    "vol",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Volume (CBM)",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="sea_freight.seashipment",
                        verbose_name="Sea Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
            },
        ),
    ]
