# Generated by Django 5.2.1 on 2026-09-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0002_container"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "2. Containers",
            },
        ),
        migrations.AlterModelOptions(
            name="seashipment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sea Shipment",
                "verbose_name_plural": "1. Sea Shipments",
            },
        ),
    ]
