# Generated by Django 5.2.1 on 2026-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0003_alter_container_options_alter_seashipment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seashipment",
            name="commodity",
            field=models.TextField(
                blank=True, help_text="شرح کالا", null=True, verbose_name="Commodity"
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="gw",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="وزن ناخالص",
                max_digits=12,
                null=True,
                verbose_name="G.W (Kg)",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="pcs",
            field=models.CharField(
                blank=True,
                help_text="تعداد و نوع بسته بندی مثل: 2 WOODEN CASES",
                max_length=50,
                null=True,
                verbose_name="Packages",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="vessel_name",
            field=models.CharField(
                blank=True,
                help_text="نام کشتی",
                max_length=100,
                null=True,
                verbose_name="Vessel",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="vol",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Volume (CBM)",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="voyage_no",
            field=models.CharField(
                blank=True,
                help_text="شماره سفر",
                max_length=30,
                null=True,
                verbose_name="Voyage No",
            ),
        ),
    ]
