# Generated by Django 5.2.1 on 2026-09-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        (
            "sea_freight",
            "0004_alter_seashipment_commodity_alter_seashipment_gw_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="seashipment",
            name="hbl_cnee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_hbl_cnee",
                to="account.consignee",
                verbose_name="MAWB Cnee",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="hbl_shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_hbl_shipper",
                to="account.shipper",
                verbose_name="MAWB Shipper",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="mbl_cnee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_mbl_cnee",
                to="account.consignee",
                verbose_name="MAWB Cnee",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="mbl_shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_mbl_shipper",
                to="account.shipper",
                verbose_name="MAWB Shipper",
            ),
        ),
    ]
