# Generated by Django 5.2.1 on 2026-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0005_alter_seashipment_hbl_cnee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seashipment",
            name="ref",
            field=models.CharField(
                blank=True,
                help_text="شماره رفرانس داخلی پرونده",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Ref",
            ),
        ),
    ]
