# Generated by Django 5.2.1 on 2026-10-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0006_alter_seashipment_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaPodList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Sea Pod"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Country Name",
                    ),
                ),
                (
                    "country_abbr",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Country Abbr"
                    ),
                ),
                (
                    "airport_abbr",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Airport Abbr"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pod",
                "verbose_name_plural": "8. Pods",
            },
        ),
        migrations.CreateModel(
            name="SeaPolList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Sea Pol"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Country Name",
                    ),
                ),
                (
                    "country_abbr",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Country Abbr"
                    ),
                ),
                (
                    "airport_abbr",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Airport Abbr"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pol",
                "verbose_name_plural": "7. Pols",
            },
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="pod",
            field=models.ForeignKey(
                help_text="Port of Discharge - بندر تخلیه",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_shipments_pod",
                to="sea_freight.seapodlist",
                verbose_name="P.O.D",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="pol",
            field=models.ForeignKey(
                help_text="Port of Loading - بندر بارگیری",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_shipments_pol",
                to="sea_freight.seapollist",
                verbose_name="P.O.L",
            ),
        ),
    ]
