# Generated by Django 5.2.1 on 2026-10-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("sea_freight", "0007_seapodlist_seapollist_alter_seashipment_pod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Sea Carrier Name"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Iran Office Address",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Iran Office Tel",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Carrier",
                "verbose_name_plural": "5. Carriers",
            },
        ),
        migrations.AlterModelOptions(
            name="seapodlist",
            options={"verbose_name": "Pod", "verbose_name_plural": "8. Sea Pods"},
        ),
        migrations.AlterModelOptions(
            name="seapollist",
            options={"verbose_name": "Pol", "verbose_name_plural": "7. Sea Pols"},
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="bl_release",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="console",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="container_type",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="delivery_agent",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="final_destination",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="mbl_cnee",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="mbl_shipper",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="movement",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="place_of_receipt",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="vessel_name",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="voyage_no",
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="hbl_cnee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_hbl_cnee",
                to="account.consignee",
                verbose_name="HBL Cnee",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="hbl_shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sea_freight_hbl_shipper",
                to="account.shipper",
                verbose_name="HBL Shipper",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="mode",
            field=models.CharField(
                choices=[
                    ("fcl", "FCL"),
                    ("lcl", "LCL"),
                    ("bb", "Break Bulk"),
                    ("b", "Bulk"),
                ],
                default="fcl",
                max_length=3,
                verbose_name="Mode",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sea_freight.seacarrier",
                verbose_name="Carrier",
            ),
        ),
    ]
