# Generated by Django 5.2.1 on 2026-10-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sea_freight", "0008_seacarrier_alter_seapodlist_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seashipment",
            name="ata",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="commodity",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="cw",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="etd",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="hscode",
        ),
    ]
